# Generated by Django 2.1.7 on 2019-02-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
